tap "clintmod/formulas"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Transfer files from and to an Android smartphone
cask "android-file-transfer"
# Application uninstaller
cask "appcleaner"
# Chromium based browser
cask "arc"
# Desktop password and login vault
cask "bitwarden"
# Universal database tool and SQL client
cask "dbeaver-community"
# Voice and text chat software
cask "discord"
# App to build and share containerised applications and microservices
cask "docker-desktop"
cask "font-jetbrains-mono"
# Cross-platform Git credential storage for multiple hosting providers
cask "git-credential-manager"
# Menu bar application that displays the CPU speed limit due to thermal issues
cask "hot"
# HTTP and GraphQL Client
cask "insomnia"
# Free cross-platform office suite, fresh version
cask "libreoffice"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Peer to peer Bitorrent client
cask "qbittorrent"
# Music streaming service
cask "spotify"
# Messaging app with a focus on speed and security
cask "telegram"
# Open-source code editor
cask "visual-studio-code"
vscode "arjun.swagger-viewer"
vscode "dunstontc.vscode-go-syntax"
vscode "golang.go"
vscode "hermitter.oh-lucy-vscode"
vscode "humao.rest-client"
vscode "redhat.vscode-yaml"
